export type BiomeId = "servers" | "cables" | "cloud";

export type EnemyDef = {
  id: string;
  nameKey: string;
  biome: BiomeId;
  health: number;
  damage: number;
  speed: number;
  attackRange: number;
  aggroRange: number;
  attackCooldown: number;
  xp: number;
  scale: number;
  color: string;
  emissive: string;
  isBoss?: boolean;
  ranged?: boolean;
};

export const BIOMES: Record<BiomeId, { id: BiomeId; nameKey: string; fogColor: string; groundColor: string; accentColor: string }> = {
  servers: {
    id: "servers",
    nameKey: "biomes.servers",
    fogColor: "#0b1220",
    groundColor: "#111a2b",
    accentColor: "#22d3ee",
  },
  cables: {
    id: "cables",
    nameKey: "biomes.cables",
    fogColor: "#0d1a12",
    groundColor: "#10241a",
    accentColor: "#4ade80",
  },
  cloud: {
    id: "cloud",
    nameKey: "biomes.cloud",
    fogColor: "#150b20",
    groundColor: "#1d1030",
    accentColor: "#c084fc",
  },
};

export const ENEMIES: EnemyDef[] = [
  {
    id: "bug",
    nameKey: "enemies.bug",
    biome: "servers",
    health: 30,
    damage: 8,
    speed: 3.2,
    attackRange: 1.6,
    aggroRange: 14,
    attackCooldown: 1.2,
    xp: 12,
    scale: 0.8,
    color: "#7f1d1d",
    emissive: "#ef4444",
  },
  {
    id: "trojan",
    nameKey: "enemies.trojan",
    biome: "servers",
    health: 55,
    damage: 12,
    speed: 2.6,
    attackRange: 1.8,
    aggroRange: 13,
    attackCooldown: 1.6,
    xp: 20,
    scale: 1.1,
    color: "#7c2d12",
    emissive: "#f97316",
  },
  {
    id: "spyware",
    nameKey: "enemies.spyware",
    biome: "servers",
    health: 24,
    damage: 9,
    speed: 2.2,
    attackRange: 10,
    aggroRange: 16,
    attackCooldown: 2.0,
    xp: 18,
    scale: 0.9,
    color: "#134e4a",
    emissive: "#2dd4bf",
    ranged: true,
  },
  {
    id: "worm",
    nameKey: "enemies.worm",
    biome: "cables",
    health: 70,
    damage: 14,
    speed: 4.0,
    attackRange: 1.7,
    aggroRange: 15,
    attackCooldown: 1.1,
    xp: 30,
    scale: 1.0,
    color: "#365314",
    emissive: "#a3e635",
  },
  {
    id: "rootkit",
    nameKey: "enemies.rootkit",
    biome: "cables",
    health: 45,
    damage: 16,
    speed: 5.2,
    attackRange: 1.5,
    aggroRange: 18,
    attackCooldown: 0.9,
    xp: 34,
    scale: 0.85,
    color: "#1e1b4b",
    emissive: "#818cf8",
  },
  {
    id: "botnet",
    nameKey: "enemies.botnet",
    biome: "cables",
    health: 20,
    damage: 7,
    speed: 3.6,
    attackRange: 1.4,
    aggroRange: 17,
    attackCooldown: 0.8,
    xp: 10,
    scale: 0.55,
    color: "#3f3f46",
    emissive: "#facc15",
  },
  {
    id: "firewall",
    nameKey: "enemies.firewall",
    biome: "cloud",
    health: 110,
    damage: 18,
    speed: 2.4,
    attackRange: 2.0,
    aggroRange: 14,
    attackCooldown: 1.8,
    xp: 55,
    scale: 1.4,
    color: "#831843",
    emissive: "#fb7185",
  },
  {
    id: "bsod_lord",
    nameKey: "enemies.bsod_lord",
    biome: "servers",
    health: 600,
    damage: 22,
    speed: 3.0,
    attackRange: 2.6,
    aggroRange: 22,
    attackCooldown: 1.4,
    xp: 250,
    scale: 2.4,
    color: "#1e3a8a",
    emissive: "#3b82f6",
    isBoss: true,
  },
  {
    id: "worm_queen",
    nameKey: "enemies.worm_queen",
    biome: "cables",
    health: 900,
    damage: 26,
    speed: 3.4,
    attackRange: 2.4,
    aggroRange: 24,
    attackCooldown: 1.2,
    xp: 400,
    scale: 2.8,
    color: "#3f6212",
    emissive: "#bef264",
    isBoss: true,
  },
  {
    id: "mainframe",
    nameKey: "enemies.mainframe",
    biome: "cloud",
    health: 1500,
    damage: 32,
    speed: 2.8,
    attackRange: 3.0,
    aggroRange: 26,
    attackCooldown: 1.3,
    xp: 800,
    scale: 3.4,
    color: "#581c87",
    emissive: "#d946ef",
    isBoss: true,
  },
];
